"""The contract. Every pydantic model the rest of the codebase types against
lives here and **only** here — API in/out, internal state, stream events,
presets, enums. Each aggregate root carries a ``schema_v``.

Import the names from this package, not the submodules, so the contract has one
public surface.
"""

from __future__ import annotations

from schemas.base import SchemaModel, StrictModel
from schemas.brief import BriefAnalysis, Change
from schemas.contract import (
    ApproveRequest,
    IngestPhotoRequest,
    IngestPhotoResponse,
    InputAnswerRequest,
    PresetAsk,
    PresetCatalog,
    PresetSummary,
    SessionAck,
    SessionSnapshot,
    StartSessionRequest,
    StartSessionResponse,
)
from schemas.enums import (
    FailureCode,
    FsmState,
    GateReason,
    PaidCallKind,
    RiskLevel,
    Verdict,
)
from schemas.events import (
    CostEvent,
    DoneEvent,
    Event,
    EventAdapter,
    FailedEvent,
    IterationResultEvent,
    IterationStartEvent,
    NeedInputEvent,
    PlanEvent,
    ResultEvent,
    RetryEvent,
    StageEvent,
    StepResultEvent,
    StepStartedEvent,
)
from schemas.inventory import PhotoInventory
from schemas.presets import (
    AppliesTo,
    Composition,
    ConvergenceProfile,
    Generation,
    Preset,
    Slot,
    Thresholds,
)
from schemas.state import (
    BestResult,
    CompositionChoice,
    ConvergenceStats,
    CostEstimate,
    EditStep,
    FaceProfile,
    FrameMetrics,
    Iteration,
    PaidCallRecord,
    Plan,
    ProviderUsage,
    SessionState,
)

__all__ = [
    "AppliesTo",
    "ApproveRequest",
    "BestResult",
    "BriefAnalysis",
    "Change",
    "Composition",
    "CompositionChoice",
    "ConvergenceProfile",
    "ConvergenceStats",
    "CostEstimate",
    "CostEvent",
    "DoneEvent",
    "EditStep",
    "Event",
    "EventAdapter",
    "FaceProfile",
    "FailedEvent",
    "FailureCode",
    "FrameMetrics",
    "FsmState",
    "GateReason",
    "Generation",
    "IngestPhotoRequest",
    "IngestPhotoResponse",
    "InputAnswerRequest",
    "Iteration",
    "IterationResultEvent",
    "IterationStartEvent",
    "NeedInputEvent",
    "PaidCallKind",
    "PaidCallRecord",
    "PhotoInventory",
    "Plan",
    "PlanEvent",
    "Preset",
    "PresetAsk",
    "PresetCatalog",
    "PresetSummary",
    "ProviderUsage",
    "ResultEvent",
    "RetryEvent",
    "RiskLevel",
    "SchemaModel",
    "SessionAck",
    "SessionSnapshot",
    "SessionState",
    "Slot",
    "StageEvent",
    "StartSessionRequest",
    "StartSessionResponse",
    "StepResultEvent",
    "StepStartedEvent",
    "StrictModel",
    "Thresholds",
    "Verdict",
]
